### ISSUE TITLE
Some cities don't have shapes

### ISSUE THREAD

**Issue by JianweiCxyz** [JianweiCxyz/UIL_webpages#6] opened 2018-03-03 06:26 UTC
![image](https://user-images.githubusercontent.com/35353979/36931353-8871f548-1e79-11e8-8fa1-11bea9c5c06c.png)

**Comment by cbischak** [comment] 2018-03-03 19:05
Origin of the problem is the KML. I will figure out why and send you a new KML File.

**Comment by JianweiCxyz** [comment] 2018-03-03 19:07
Well, if a new kml is needed, please update the new color scheme as well.

**Comment by cbischak** [comment] 2018-03-03 19:11
Ok. I am working on it now. I will update everything through the KML file.

**Comment by cbischak** [comment] 2018-03-03 20:08
Should be fixed with most to date KML_File once it is added to Fusion Table

**Comment by JianweiCxyz** [comment] 2018-03-04 02:15
See http://utw10792.utweb.utexas.edu/test4/ .
Boston fixed. Phoenix still don't have shapes.

**Comment by cbischak** [comment] 2018-03-04 15:54
Fingers crossed #25 will fix this issue with the updated kml file

**Comment by JianweiCxyz** [comment] 2018-03-04 19:46
Fixed with https://github.com/JianweiCxyz/UIL_webpages/commit/bea234ff651314b31c5346a51d13be562fdf79a4

**Closed** 2018-03-04 19:47 UTC
Labels: High Priority
